version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 99
  assignees:
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.871.0
    - 2.889.0
    - 2.892.0
